# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

dist: precise

language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.4
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/cms:^3.4
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit siteconfig/tests
